run:
  tests: false
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - godot
    - godox
    - gofmt
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unused
    - varcheck
